spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.127.129:8848
    gateway:
      routes:
        - id: test_rout
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq_rout
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
        - id: product-route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        - id: coupon-route
          uri: lb://gulimall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        - id: member-route
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        - id: order-route
          uri: lb://gulimall-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        - id: ware-route
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        - id: thirdparty-route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        - id: admin-route
          uri: lb://renren-fast-master
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}

  application:
    name: gulimall-gateway
server:
  port: 88